"""Relational Operators"""
__author__ = "730234891"
x: str = input("Left-hand side : ")
y: str = input("Right-hand side : ")
t1_new = bool(x) < bool(y)
ro = str(t1_new)
print(x + " < " + y + "is " + ro)
t2_new = bool(x) >= bool(y)
r1 = str(t2_new)
print(x + " >= " + y + "is " + r1)
t3_new = bool(x) == bool(y)
r2 = str(t3_new)
print(x + " == " + y + "is " + r2)
t4_new = bool(x) != bool(y)
r3 = str(t4_new)
print(x + " != " + y + "is " + r3)